[phases.setup]
nixPkgs = [
  "chromium",
  "xvfb-run",
  "libxkbcommon",
  "xorg.libxkbfile",
  "xorg.libXrandr",
  "xorg.libXinerama",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXtst",
  "xorg.libXScrnSaver",
  "xorg.libXext",
  "xorg.libXdamage",
  "xorg.libXcomposite",
  "xorg.libXrender",
  "freetype",
  "fontconfig",
  "libuuid",
  "libpulseaudio",
  "alsa-lib",
  "at-spi2-core",
  "dbus",
  "glib",
  "gtk3",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "cups",
  "nspr",
  "nss",
  "libnotify",
]
